### ISSUE TITLE
Feature Request : customize the QML code edit

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rcse#16]
Hello,

Could it be possible to create a separate text box to add additional QML code or to put in the edited one so it would be apply over the generated code at the end of the "Generate Code and Sheet" process.

So we could "Generate Code and Sheet" again and again without loosing the custom code.

**Comment by obiwankennedy** [comment]
Hi, this features is already done. 
I don't remember if I made it in rcse released with rolisteam 1.8.2 but it is already done for sure in 1.9.0.

As you can edit the generated code of any field. So instead of generate its code, the field just copy and paste its code with the user modification. 
Additionally to that, Editing property of the sheet, allows user to define QML at the beginning or (exclusive or) the end of the qml file. (In v1.9, it will be available for both side at the same time).

I also make the view and the qml code on the same tab. So it is easier to see modification without switching tabs all the time.
I also improve a bit the editor, using font with fixed case.
