### ISSUE TITLE
Background not displaying on multiple page Character Sheet

### ISSUE THREAD

**Issue by derpmonog** [Rolisteam/rcse#17]
When creating a 3 page character sheet only one background image will appear. All threee resolution are the same and are the same format.
![pg1e](https://user-images.githubusercontent.com/46627907/51250729-4ca84c00-1965-11e9-8788-6b7a761c8dd7.png)
![pg2e](https://user-images.githubusercontent.com/46627907/51250744-5fbb1c00-1965-11e9-86bc-b645e6d14348.png)
![pg3e](https://user-images.githubusercontent.com/46627907/51250748-62b60c80-1965-11e9-8c2a-732d3233b2c1.png)
![pg1v](https://user-images.githubusercontent.com/46627907/51250760-6d70a180-1965-11e9-96d6-163351ad3930.png)
![pg2v](https://user-images.githubusercontent.com/46627907/51250761-6ea1ce80-1965-11e9-8efd-fad65b0341e6.png)
![pg3v](https://user-images.githubusercontent.com/46627907/51250762-6fd2fb80-1965-11e9-83a4-1cc7b287f20e.png)

**Comment by obiwankennedy** [comment]
It happens when you add pages after loading the sheet.
RCSE is a bit fragile. The best way is to create the sheet completely (save frequently) but don't close RCSE. When you load already created sheet.

But don't worry it is easy to fix. If you can add your charactersheet in this thread (in a zip archive), i will be able to send you a fixed version.

RCS file are just json file so it is possible to fix up sheet easily.

__
Next release of RCSE will bring many improvements in that matter. RCSE will work like a charm

**Comment by derpmonog** [comment]
[5ezip.zip](https://github.com/Rolisteam/rcse/files/2768800/5ezip.zip)
Here is the sheet ive included the background images as well in case you need them

**Comment by obiwankennedy** [comment]
[5esheet_fixed.zip](https://github.com/Rolisteam/rcse/files/2770320/5esheet_fixed.zip)
